<CoquiAPIWidget>:
    md_bg_color: self.theme_cls.secondaryContainerColor

    voice_selection: voice_name_spinner
    model_selection: model_spinner

    MDBoxLayout:
        orientation: "vertical"
        MDTopAppBar:
            type: "small"
            pos_hint: {"center_x": .5, "top": 1}
            MDTopAppBarLeadingButtonContainer:
                spacing: "4dp"
                padding: 40,0,0,5
                MDActionTopAppBarButton:
                    id: btn_back
                    icon: "arrow-left"
                    height: "56dp"
                    on_release:
                        root.manager.transition.direction = 'right'
                        root.manager.current = "settings"
            MDTopAppBarTitle:
                text: root.title
                pos_hint: {"center_x": .5, "center_y": .5}
        MDDivider:
            size_hint_x: 0.8
            pos_hint: {"center_x": .5, "center_y": .5}
        MDScrollView:
            adaptive_height: True
            size_hint_x: 1
            pos_hint: {"center_x": .5, "center_y": .5}
            MDList:
                id: settings_container
                MDListItem:
                    MDButton:
                        id: btn_test_api_key
                        pos_hint: {"center_x": .5, "center_y": .5}
                        size_hint_x: 0.8
                        on_release: root.init_api()
                        MDButtonText:
                            text: "Init API"
                MDListItem:
                    height: "120dp"
                    MDListItemLeadingIcon:
                        icon: "account-voice"
                        pos_hint: {"center_x": .5, "center_y": .5}
                    MDListItemHeadlineText:
                        text: 'Voice:'
                    MDListItemSupportingText:
                        text: "Select the voice that you want to use."
                    Spinner:
                        id: voice_name_spinner
                        text: root.get_current_voice() if root.get_current_voice() else 'No voices available'
                        values: root.voice_names
                MDListItem:
                    height: "120dp"
                    MDListItemLeadingIcon:
                        icon: "account-cog"
                        pos_hint: {"center_x": .5, "center_y": .5}
                    MDListItemHeadlineText:
                        text: 'Model:'
                    Spinner:
                        id: model_spinner
                        text: root.model_names[0] if root.model_names else 'No models available'
                        values: root.model_names